export enum ProductCategory {
  COFFEE = 'COFFEE',
  TEA = 'TEA',
  PASTRY = 'PASTRY',
  SANDWICH = 'SANDWICH',
  SNACK = 'SNACK',
  COLD_DRINKS = 'COLD_DRINKS',
  FRESH_JUICE = 'FRESH_JUICE',
  HOT_BEVERAGES = 'HOT_BEVERAGES',
  LEMONADES = 'LEMONADES',
  ADDITIVES = 'ADDITIVES',
  OTHER = 'OTHER'
} 